import { User, AttendanceRecord, LeaveRequest, NotificationItem } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    employeeId: 'EMP-001',
    email: 'alex.admin@dayflow.internal',
    role: 'ADMIN',
    isVerified: true,
    profile: {
      firstName: 'Alex',
      lastName: 'Morgan',
      phone: '+1 (555) 234-5678',
      address: '742 Evergreen Terrace, Tech District, SF, CA 94107',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      department: 'Executive HR',
      designation: 'VP of People & Culture / Admin',
      dateOfJoining: '2022-01-15',
      employeeId: 'EMP-001',
      email: 'alex.admin@dayflow.internal',
      emergencyContact: '+1 (555) 987-6543 (Spouse)',
      skills: ['Strategic HR', 'Workplace Policy', 'Talent Acquisition', 'Payroll Audit'],
      documents: [
        { id: 'doc-1', name: 'Executive_Offer_Letter.pdf', type: 'PDF', size: '1.8 MB', uploadDate: '2022-01-15' },
        { id: 'doc-2', name: 'NDA_Confidentiality_Signed.pdf', type: 'PDF', size: '850 KB', uploadDate: '2022-01-15' },
        { id: 'doc-3', name: 'Identity_Passport_Copy.pdf', type: 'PDF', size: '2.4 MB', uploadDate: '2022-01-16' },
      ],
    },
    salary: {
      basicSalary: 9500,
      hra: 3800,
      allowances: 2200,
      deductions: 2100,
      netSalary: 13400,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 8842',
      bankName: 'Silicon Valley National Bank',
      panOrTaxId: 'US-TX-9938210',
    },
  },
  {
    id: 'user-2',
    employeeId: 'EMP-002',
    email: 'elena.hr@dayflow.internal',
    role: 'HR_OFFICER',
    isVerified: true,
    profile: {
      firstName: 'Elena',
      lastName: 'Rostova',
      phone: '+1 (555) 345-6789',
      address: '128 Mission Bay Blvd, Suite 400, SF, CA 94158',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      department: 'Human Resources',
      designation: 'Lead People Operations Specialist',
      dateOfJoining: '2022-06-01',
      employeeId: 'EMP-002',
      email: 'elena.hr@dayflow.internal',
      emergencyContact: '+1 (555) 876-5432 (Brother)',
      skills: ['Employee Relations', 'HR Compliance', 'Benefits Admin', 'Onboarding'],
      documents: [
        { id: 'doc-4', name: 'Employment_Contract_Elena.pdf', type: 'PDF', size: '1.4 MB', uploadDate: '2022-06-01' },
        { id: 'doc-5', name: 'HR_Certifications_SHRM.pdf', type: 'PDF', size: '3.1 MB', uploadDate: '2022-06-05' },
      ],
    },
    salary: {
      basicSalary: 6200,
      hra: 2400,
      allowances: 1400,
      deductions: 1350,
      netSalary: 8650,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 3190',
      bankName: 'Chase Commercial Bank',
      panOrTaxId: 'US-TX-4401923',
    },
  },
  {
    id: 'user-3',
    employeeId: 'EMP-003',
    email: 'liam.chen@dayflow.internal',
    role: 'EMPLOYEE',
    isVerified: true,
    profile: {
      firstName: 'Liam',
      lastName: 'Chen',
      phone: '+1 (555) 456-7890',
      address: '520 King Street, Apt 12B, Seattle, WA 98104',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      department: 'Engineering',
      designation: 'Senior Staff Frontend Architect',
      dateOfJoining: '2023-02-10',
      employeeId: 'EMP-003',
      email: 'liam.chen@dayflow.internal',
      emergencyContact: '+1 (555) 654-3210 (Partner)',
      skills: ['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'GraphQL', 'Web Performance'],
      documents: [
        { id: 'doc-6', name: 'Liam_Chen_Offer_Letter.pdf', type: 'PDF', size: '1.2 MB', uploadDate: '2023-02-10' },
        { id: 'doc-7', name: 'Tax_Exemption_Form_W4.pdf', type: 'PDF', size: '620 KB', uploadDate: '2023-02-12' },
        { id: 'doc-8', name: 'Direct_Deposit_Voided_Check.pdf', type: 'PDF', size: '480 KB', uploadDate: '2023-02-12' },
      ],
    },
    salary: {
      basicSalary: 7500,
      hra: 3000,
      allowances: 1800,
      deductions: 1750,
      netSalary: 10550,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 5521',
      bankName: 'Bank of America',
      panOrTaxId: 'US-TX-8829104',
    },
  },
  {
    id: 'user-4',
    employeeId: 'EMP-004',
    email: 'sophia.taylor@dayflow.internal',
    role: 'EMPLOYEE',
    isVerified: true,
    profile: {
      firstName: 'Sophia',
      lastName: 'Taylor',
      phone: '+1 (555) 567-8901',
      address: '310 S Broadway, Loft 5A, Los Angeles, CA 90013',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      department: 'Product Design',
      designation: 'Lead Product & UX Designer',
      dateOfJoining: '2023-04-18',
      employeeId: 'EMP-004',
      email: 'sophia.taylor@dayflow.internal',
      emergencyContact: '+1 (555) 432-1098 (Mother)',
      skills: ['Design Systems', 'Figma', 'User Research', 'Prototyping', 'Accessibility'],
      documents: [
        { id: 'doc-9', name: 'Sophia_Offer_Contract.pdf', type: 'PDF', size: '1.1 MB', uploadDate: '2023-04-18' },
        { id: 'doc-10', name: 'IP_Assignment_Agreement.pdf', type: 'PDF', size: '920 KB', uploadDate: '2023-04-19' },
      ],
    },
    salary: {
      basicSalary: 6800,
      hra: 2700,
      allowances: 1600,
      deductions: 1550,
      netSalary: 9550,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 7712',
      bankName: 'Wells Fargo',
      panOrTaxId: 'US-TX-3329011',
    },
  },
  {
    id: 'user-5',
    employeeId: 'EMP-005',
    email: 'marcus.vance@dayflow.internal',
    role: 'EMPLOYEE',
    isVerified: true,
    profile: {
      firstName: 'Marcus',
      lastName: 'Vance',
      phone: '+1 (555) 678-9012',
      address: '88 Austin St, Unit 302, Austin, TX 78701',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      department: 'Engineering',
      designation: 'Full Stack Backend Developer',
      dateOfJoining: '2023-08-01',
      employeeId: 'EMP-005',
      email: 'marcus.vance@dayflow.internal',
      emergencyContact: '+1 (555) 321-0987 (Father)',
      skills: ['Node.js', 'PostgreSQL', 'Prisma', 'Redis', 'Docker', 'REST APIs'],
      documents: [
        { id: 'doc-11', name: 'Marcus_Offer_Letter.pdf', type: 'PDF', size: '1.3 MB', uploadDate: '2023-08-01' },
      ],
    },
    salary: {
      basicSalary: 5900,
      hra: 2200,
      allowances: 1300,
      deductions: 1250,
      netSalary: 8150,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 9014',
      bankName: 'PNC Bank',
      panOrTaxId: 'US-TX-6610293',
    },
  },
  {
    id: 'user-6',
    employeeId: 'EMP-006',
    email: 'aria.patel@dayflow.internal',
    role: 'EMPLOYEE',
    isVerified: true,
    profile: {
      firstName: 'Aria',
      lastName: 'Patel',
      phone: '+1 (555) 789-0123',
      address: '450 Cambridge Parkway, Boston, MA 02142',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      department: 'Infrastructure',
      designation: 'DevOps & Site Reliability Engineer',
      dateOfJoining: '2023-10-15',
      employeeId: 'EMP-006',
      email: 'aria.patel@dayflow.internal',
      skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD', 'Security Audits'],
      documents: [
        { id: 'doc-12', name: 'Aria_Patel_Contract.pdf', type: 'PDF', size: '1.5 MB', uploadDate: '2023-10-15' },
      ],
    },
    salary: {
      basicSalary: 6400,
      hra: 2500,
      allowances: 1500,
      deductions: 1400,
      netSalary: 9000,
      currency: 'USD',
      effectiveFrom: '2024-01-01',
      bankAccount: '•••• •••• •••• 4429',
      bankName: 'Citibank',
      panOrTaxId: 'US-TX-7718290',
    },
  }
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'leave-1',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    leaveType: 'PAID',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    totalDays: 3,
    reason: 'Attending Next.js Global Conf 2026 as speaker and taking couple of personal days.',
    status: 'PENDING',
    createdAt: '2026-08-21',
  },
  {
    id: 'leave-2',
    userId: 'user-4',
    employeeName: 'Sophia Taylor',
    employeeId: 'EMP-004',
    department: 'Product Design',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    leaveType: 'SICK',
    startDate: '2026-08-24',
    endDate: '2026-08-24',
    totalDays: 1,
    reason: 'Scheduled dental oral surgery follow-up and rest day.',
    status: 'PENDING',
    createdAt: '2026-08-22',
  },
  {
    id: 'leave-3',
    userId: 'user-5',
    employeeName: 'Marcus Vance',
    employeeId: 'EMP-005',
    department: 'Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    leaveType: 'PAID',
    startDate: '2026-08-10',
    endDate: '2026-08-14',
    totalDays: 5,
    reason: 'Family summer vacation travel.',
    status: 'APPROVED',
    adminRemarks: 'Approved by HR. Have a great vacation Marcus!',
    reviewedBy: 'Elena Rostova (HR)',
    createdAt: '2026-08-01',
  },
  {
    id: 'leave-4',
    userId: 'user-6',
    employeeName: 'Aria Patel',
    employeeId: 'EMP-006',
    department: 'Infrastructure',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    leaveType: 'UNPAID',
    startDate: '2026-07-20',
    endDate: '2026-07-21',
    totalDays: 2,
    reason: 'Relocating home apartments.',
    status: 'APPROVED',
    adminRemarks: 'Approved without pay deduction override.',
    reviewedBy: 'Alex Morgan (Admin)',
    createdAt: '2026-07-15',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today's attendance records (2026-08-22)
  {
    id: 'att-today-1',
    userId: 'user-1',
    employeeName: 'Alex Morgan',
    employeeId: 'EMP-001',
    department: 'Executive HR',
    date: '2026-08-22',
    checkIn: '08:45 AM',
    checkOut: null,
    totalHours: 4.5,
    status: 'PRESENT',
    remarks: 'Early morning board review'
  },
  {
    id: 'att-today-2',
    userId: 'user-2',
    employeeName: 'Elena Rostova',
    employeeId: 'EMP-002',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '09:02 AM',
    checkOut: null,
    totalHours: 4.2,
    status: 'PRESENT',
    remarks: 'Onboarding new cohort'
  },
  {
    id: 'att-today-3',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:15 AM',
    checkOut: null,
    totalHours: 4.0,
    status: 'PRESENT',
    remarks: 'Sprint planning & core UI'
  },
  {
    id: 'att-today-4',
    userId: 'user-4',
    employeeName: 'Sophia Taylor',
    employeeId: 'EMP-004',
    department: 'Product Design',
    date: '2026-08-22',
    checkIn: '09:30 AM',
    checkOut: null,
    totalHours: 3.8,
    status: 'PRESENT',
    remarks: 'Design system review'
  },
  {
    id: 'att-today-5',
    userId: 'user-5',
    employeeName: 'Marcus Vance',
    employeeId: 'EMP-005',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    totalHours: 0,
    status: 'ABSENT',
    remarks: 'Unreported absent / Remote standby'
  },
  {
    id: 'att-today-6',
    userId: 'user-6',
    employeeName: 'Aria Patel',
    employeeId: 'EMP-006',
    department: 'Infrastructure',
    date: '2026-08-22',
    checkIn: '09:00 AM',
    checkOut: '01:15 PM',
    totalHours: 4.25,
    status: 'HALF_DAY',
    remarks: 'Half day approved for infrastructure cert exam'
  },
  
  // Historical Records for Liam Chen (EMP-003)
  {
    id: 'att-hist-1',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-21',
    checkIn: '09:05 AM',
    checkOut: '05:40 PM',
    totalHours: 8.58,
    status: 'PRESENT',
    remarks: 'Frontend release candidate'
  },
  {
    id: 'att-hist-2',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-20',
    checkIn: '08:58 AM',
    checkOut: '05:30 PM',
    totalHours: 8.53,
    status: 'PRESENT',
  },
  {
    id: 'att-hist-3',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-19',
    checkIn: '09:12 AM',
    checkOut: '06:00 PM',
    totalHours: 8.8,
    status: 'PRESENT',
  },
  {
    id: 'att-hist-4',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-18',
    checkIn: '09:20 AM',
    checkOut: '01:30 PM',
    totalHours: 4.16,
    status: 'HALF_DAY',
    remarks: 'Medical checkup afternoon'
  },
  {
    id: 'att-hist-5',
    userId: 'user-3',
    employeeName: 'Liam Chen',
    employeeId: 'EMP-003',
    department: 'Engineering',
    date: '2026-08-15',
    checkIn: '09:00 AM',
    checkOut: '05:15 PM',
    totalHours: 8.25,
    status: 'PRESENT',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Salary Slip Available',
    message: 'Your official July 2026 salary statement is ready to view & download.',
    type: 'payroll',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Leave Request Received',
    message: 'Liam Chen submitted a Paid Leave application for Aug 28-30.',
    type: 'leave',
    timestamp: 'Yesterday',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'System Welcome',
    message: 'Welcome to Dayflow HRMS v2.4. Every workday, perfectly aligned.',
    type: 'system',
    timestamp: '3 days ago',
    read: true,
  }
];
